# Generated by Django 3.2.8 on 2022-01-21 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Hospital', '0003_opinion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_of_visit', models.CharField(blank=True, choices=[('Anulowana', 'Anulowana'), ('Zaakceptowana', 'Zaakceptowana'), ('OczekujeNaAkceptacje', 'Oczekuje na akceptacje')], max_length=20, null=True)),
                ('date_of_visit', models.DateTimeField(verbose_name='Termin wizyty')),
                ('extra_info', models.TextField(blank=True, max_length=200, null=True, verbose_name='Dodatkowe informacje')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hospital.doctor', verbose_name='Wizyta u lekarza:')),
            ],
        ),
    ]
