# Generated by Django 3.2.8 on 2022-01-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0004_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='firstname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Imie'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='imgs/'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='lastname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nazwisko'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='room',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Nr gabinetu'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='typeofdoctor',
            field=models.CharField(blank=True, choices=[('Chirurg', 'Chirurg'), ('Neurochirurg', 'Neurochirurg'), ('Kardiolog', 'Kardiolog'), ('Neurolog', 'Neurolog'), ('Okulista', 'Okulista'), ('Urolog', 'Urolog'), ('Alergolog', 'Alergolog'), ('Onkolog', 'Onkolog')], max_length=50, null=True, verbose_name='Specjalizacja'),
        ),
    ]
